### ISSUE TITLE
Implement additional service providers

### ISSUE THREAD

**Issue by gwn** [api3dao/api3-web-client#19]
We already have support for MetaMask and WalletConnect but we may need to add support for other providers as well.

For reference here is the list of the providers that our web3 solution supports:
https://github.com/NoahZinsmeister/web3-react/tree/v6/packages

**Comment by gwn** [comment]
@bbenligiray any requirements & requests here?

**Comment by bbenligiray** [comment]
The two should suffice for now

**Comment by gwn** [comment]
> Btw I was told that the public WalletConnect bridge can only be used for sending transactions but not for view calls. Can you verify that?

Interesting. I'm not sure, it may be right. But in any case I think it's a too low level fact to concern us and I believe the WalletConnect connector abstraction we're making use of is already dealing with that. Here is the part where we initialize the WalletConnectConnector:
https://github.com/api3dao/api3-web-client/blob/master/src/lib/web3/config.js#L19-L26

That `rpc` parameter is required. (For information, we're making use of Infura URLs for the Mainnet and Rinkeby URLs). I've always wondered why WalletConnect needed those URLs and not make use of its own connection for everything. Maybe the reason is what you're saying about the bridge, and the connector is falling back to those URLs for view calls.

In any case, I think the connector covers it for us. Never had any problems until now. (This is the 3rd project in which I'm making use of this library)

**Comment by gwn** [comment]
> The two should suffice for now.

Then I'm closing the issue. We can open a new one when we feel the need to add new providers in the future.
