### ISSUE TITLE
DAO Pool

### ISSUE THREAD

**Issue by gwn** [api3dao/api3-web-client#2]
![insurance-pool](https://user-images.githubusercontent.com/1702469/114019250-d7433180-9876-11eb-8bcc-c2bd45922d85.png)

**Comment by bbenligiray** [comment]
FYI we want "insurance pool" to read "DAO pool" instead

**Comment by Peartes** [comment]
Is this a purely UI-related task, I mean does the reading DAO pool mean display "DAO pool" or the data displayed are to be read from something called a DAO pool?

**Comment by gwn** [comment]
> Is this a purely UI-related task, I mean does the reading DAO pool mean display "DAO pool" or the data displayed are to be read from something called a DAO pool?

@Peartes the numbers you see in the image come from the Api3Pool contract. The task is to figure out which contract methods to use to get these numbers, and then implement the UI.

If you get a hard time figuring it out, please see the sections "contract interaction" & "contract docs" in the [backend local setup guide](https://github.com/api3dao/api3-dao/blob/devtools/packages/pool/eges-guide-to-local-setup-and-discovery.md) I prepared earlier. If you follow the instructions there then you should be able to make the discoveries you need with relative ease.

If you still cannot figure out please get help from the backend team. They will most likely know which methods to use to get which number.

If you still cannot figure out even with the backend team's help, please notify me.

**Comment by Peartes** [comment]
Okay this is clearer

**Comment by gwn** [comment]
@bbenligiray we need an exact formula to calculate the APY value as it is seen on the screenshot. We have the APR value on the pool contract but as far as I know it's not really the same as APY.

Another thing is that I don't know where to get the annual inflation rate value.

Please advise.

**Comment by bbenligiray** [comment]
Below gives the APY in percentages, meaning that for a `currentApr` of 75,000,000 (75%), it will be 110.5689140647931 (in percentages)
```js
currentApy = Math.pow(1 + currentApr / 100000000 / 52, 52) - 1;
```
Note that currently 100% is represented as 100,000,000. An audit report suggests it should be 10^18 instead. In that case, this formula will need to be updated.

Annual inflation rate (in percentages):
```
annualMintedTokens = api3Pool.totalStake() * currentApy / 100;
annualInflationRate = annualMintedTokens / (annualMintedTokens + api3Token.totalSupply()) * 100;
```
So at a `currentApr` of 75%, 50,000,000 tokens staked and 100,000,000 token total supply, annual inflation rate is 35.602054506 (in percentages). (People lurking, APR will not be 75% straight, dashboard only displays an extrapolation)

**Comment by gwn** [comment]
Thank you for the formulas @bbenligiray . One clarification needed though:

> Below gives the APY in percentages, meaning that for a currentApr of 75,000,000 (75%), it will be 110.5689140647931 (in percentages)
>
> `currentApy = Math.pow(1 + currentApr / 100000000 / 52, 52) - 1;`

This formula is returning `1.105689140647931` to me and not `110.5689140647931`. Can you make sure that the formula is correct?

The other formula is fine.

**Comment by bbenligiray** [comment]
Yeah sorry, it needs to be multiplied by 100 too

**Comment by gwn** [comment]
Implemented in:
https://github.com/api3dao/api3-web-client/commit/e4af2db56bb9b3ec411977dd9910466882ae932f
https://github.com/api3dao/api3-web-client/commit/e364d8a5b7b64a8dca3b7d1ae3405c67d7072660
