### ISSUE TITLE
Incorrect total pool stake

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/api3-web-client#4]
Not all tokens at the pool are staked. This
https://github.com/gwn/api3-web-client/blob/master/src/lib/web3/config.js#L63
should be using this instead
https://github.com/api3dao/api3-dao/blob/develop/packages/pool/contracts/StateUtils.sol#L120

**Comment by bbenligiray** [comment]
I noticed that `stakeAmount` is being used like the amount specific to the user.Use the method below for that.
https://github.com/api3dao/api3-dao/blob/develop/packages/pool/contracts/GetterUtils.sol#L150

**Comment by gwn** [comment]
Thank you for your guidance. Fixed: https://github.com/api3dao/api3-web-client/commit/6808d93868a8a4eb593c1d74bbd616ac66a83c15
