### ISSUE TITLE
User should approve infinite tokens before depositing

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/api3-web-client#5]
Here
https://github.com/gwn/api3-web-client/blob/master/src/lib/web3/config.js#L103
the user approves the exact amount they will deposit.
Instead, the user should first approve infinite tokens (https://coinmarketcap.com/alexandria/glossary/infinite-approval) before depositing any tokens (the deposit button should be replaced by an approve button).

**Comment by gwn** [comment]
Fixed with https://github.com/api3dao/api3-web-client/pull/9
