### ISSUE TITLE
There is no wallet balance display

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/api3-web-client#7]
In the wireframes, there is no wallet balance display (how many API3 I have in my wallet). The unstaked amount being displayed on the dashboard is the amount that is deposited but not staked. We have two options
1. Don't display it, their wallet plug-in will anyway
2. Add it to the wireframe

**Comment by bbenligiray** [comment]
On second thought, let's add this inside the deposit modal. So when you click deposit and the modal with the textbox pops up, it says "Undeposited: 1234" above the textbox.

**Comment by gwn** [comment]
Implemented in https://github.com/api3dao/api3-web-client/commit/25e2b4e79362c84f480d4018a058eb9bfe8112f5
